# Generated by Django 3.2.8 on 2021-11-23 00:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Compartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('ocupado', models.BooleanField(default=False)),
                ('armario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartimentos', to='codex.armario')),
            ],
            options={
                'ordering': ['descricao'],
                'unique_together': {('armario', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_resgate', models.CharField(blank=True, max_length=45)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StatusFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=256)),
                ('senha', models.CharField(blank=True, max_length=256)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=13)),
                ('ativo', models.BooleanField(blank=True, default='1')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='codex.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(blank=True, max_length=45)),
                ('andar', models.CharField(blank=True, max_length=45)),
                ('unidade', models.CharField(blank=True, max_length=45)),
                ('pessoa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='codex.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='FilaEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('data_saida', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.encomenda')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.pessoa')),
                ('status_fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.statusfila')),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaCompartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.compartimento')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.encomenda')),
            ],
        ),
        migrations.AddField(
            model_name='encomenda',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.pessoa'),
        ),
    ]
