# Generated by Django 3.2.7 on 2021-09-30 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=256)),
                ('senha', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateTimeField()),
                ('telefone', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=13)),
                ('ativo', models.BooleanField(default='1')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_resgate', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=45)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.pessoa')),
            ],
        ),
    ]
