# Generated by Django 3.2.8 on 2021-10-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_statusfila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Compartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('ocupado', models.BooleanField(default=False)),
                ('armario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.armario')),
            ],
        ),
        migrations.CreateModel(
            name='FilaEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.encomenda')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.pessoa')),
                ('status_fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.statusfila')),
            ],
        ),
        migrations.CreateModel(
            name='EncomendaCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartilhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.compartilhamento')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.encomenda')),
            ],
        ),
    ]
